version: '3.8'

services:


  redis:
    image: redis:7-alpine
    container_name: divine_hindu_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: divine_hindu_backend
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - .env:/app/.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@host.docker.internal:3306/divine_hindu_crm
      - REDIS_URL=redis://redis:6379/0

  celery_worker:
    build: ./backend
    container_name: divine_hindu_celery_worker
    restart: always
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - ./backend:/app
      - .env:/app/.env
    depends_on:
      - redis
      - backend
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@host.docker.internal:3306/divine_hindu_crm
      - REDIS_URL=redis://redis:6379/0

  celery_beat:
    build: ./backend
    container_name: divine_hindu_celery_beat
    restart: always
    command: celery -A app.tasks.celery_app beat --loglevel=info
    volumes:
      - ./backend:/app
      - .env:/app/.env
    depends_on:
      - redis
      - celery_worker
    environment:
      - DATABASE_URL=mysql+pymysql://root:root@host.docker.internal:3306/divine_hindu_crm
      - REDIS_URL=redis://redis:6379/0

volumes:
  redis_data:
