"""add smart routing

Revision ID: 896ac96827f9
Revises: 
Create Date: 2026-06-18 15:13:36.673614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896ac96827f9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('agents', sa.Column('conversion_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'conversion_rate')
    op.drop_column('agents', 'city')
    # ### end Alembic commands ###
